project_name: go-template
builds:
  - binary: go-template
    ldflags: -s -w -X go-template/cmd/version.Version={{.Version}} -X go-template/cmd/version.Commit={{.Commit}} -X go-template/cmd/version.Date={{.Date}} -extldflags "-static"
    flags: -a
    main: ./go-template/main.go
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - x86

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  # Allows you to change the name of the generated snapshot
  # releases. The following variables are available:
  # - Commit
  # - Tag
  # - Timestamp
  # Default is `SNAPSHOT-{{.Commit}}`.
  name_template: SNAPSHOT-{{.Commit}}

nfpm:
    vendor: Sascha Andres
    homepage: https://livingit.de
    maintainer: Sascha Andres <sascha.andres@outlook.com>
    description: template tool for projects
    license: Apache 2.0
    formats:
      - deb
    dependencies:
      - git
    bindir: /usr/local/bin

release:
  draft: true
  github:
      owner: sascha-andres
      name: go-template

